//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.12 at 08:25:31 PM BST 
//


package com.cogniwire.etlPipeline.model;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cogniwire.etlpipeline.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MsgDesc_QNAME = new QName("", "MsgDesc");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cogniwire.etlpipeline.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VoucherEntry }
     * 
     */
    public VoucherEntry createVoucherEntry() {
        return new VoucherEntry();
    }

    /**
     * Create an instance of {@link VoucherEntry.Record }
     * 
     */
    public VoucherEntry.Record createVoucherEntryRecord() {
        return new VoucherEntry.Record();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MsgDesc", defaultValue = "Sample voucher message between System A and System B")
    public JAXBElement<String> createMsgDesc(String value) {
        return new JAXBElement<String>(_MsgDesc_QNAME, String.class, null, value);
    }

}
